/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hp' at '31/10/20 1:08 PM' with Gradle 3.0
 *
 * @author Hp, @date 31/10/20 1:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
